sudo: false
language: python
python:
- '2.7'
- '3.6'
before_script:
- pip install -r requirements.txt
- pip install coverage
- pip install python-coveralls
- pip install pycodestyle
- npm install -g jshint
- cp travis-ci/manage.py manage.py
script:
- pycodestyle anonymous_feedback/ --exclude=migrations
- jshint anonymous_feedback/static/anonymous_feedback/js/ --verbose
- coverage run --source=anonymous_feedback/ manage.py test anonymous_feedback
after_success:
- coveralls
before_deploy:
- find anonymous_feedback/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > anonymous_feedback/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: rtD2wcRSl1RNq9cvnpnth7q2w3XTjD1WSnS6rEOu/wC9fCxFAnA7CidTa4WUPminza05gD6V02bsNXpVi21dU3ujPlCxfAxV9PvcvJWjaG9BOoew5BIwfH0pfZ+b/pylpOnLe6Pwlxo+RiDC/uLIfPOYkhOu2SMkZvOSqnrVpl81sxawwH620qomStQfGV0aBhbArUduIHG3RS1/D38AsDH1nAIQ1Ahu1n8YqEXK/X2hob5B/UlHUBKY67wSGkmHnMCLGM2xtqrFVDSy4SvOQnoXm0gob+RWuDFSrTO3qqPgUXgHmNquviOLmiXPbkQAoP68OdfzoPiRWTWSvFepbSX4n9FO/rP0f6J2E90UuNDum/xWoBKMhJ8sWgOEhZwBv/3Ddp5v+CyfV+LbLdBrMlxwXPJom096D1vzL4cawlvvc6d3RfU4+n5x4BjS6H22VEmnNWBFD9vvutzP3qNecXi5M8lQa2wABUvBHUb6FXB4W1PizseQ201BQRntT+YpLHnaLNT5w7d5V7T8yh9nija7mhsjNEwPPm+ch/GMQIxra+aflQMjqkWZlqBHox774T3XmjPCmvuWsCNaWpAj6ko8JidMPouERzp8vLBHZ3bPur/mPbFZfsgJDbGVva+60wAwjtbE0bwnng6fNOrq4rS8ezGak9UPYhNBZSyO548=
  on:
    tags: true
    python: '3.6'
