sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
- pip install -r requirements.txt
- pip install coverage
- pip install python-coveralls
- pip install pycodestyle
- npm install -g jshint
- cp travis-ci/manage.py manage.py
script:
- pycodestyle anonymous_feedback/ --exclude=migrations
- jshint anonymous_feedback/static/anonymous_feedback/js/ --verbose
- coverage run --source=anonymous_feedback/ manage.py test anonymous_feedback
after_success:
- coveralls
before_deploy:
- find anonymous_feedback/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > anonymous_feedback/VERSION
