# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(null=True)),
                ('sender_type', models.CharField(choices=[(b'anonymous', b'Anonymous'), (b'optional', b'Optional'), (b'required', b'Required')], default=b'anonymous', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
