# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
